server:
  port: 8012

spring:
  application:
    name: springcloud-alibaba-feign-consumer
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
        register-enabled: true

feign:
  hystrix:
    enabled: true
ribbon:
    OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
    ReadTimeout: 3100   #负载均衡超时时间，默认值1000
    ConnectTimeout: 2000 #ribbon请求连接的超时时间，默认值2000
    MaxAutoRetries: 0     #对当前实例的重试次数，默认0
    MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000 #断路器超时时间，默认1000ms


